services:
  # API Backend
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=development
      - DEBUG=True
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: sh -c "sleep 10 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  # Base de datos PostgreSQL
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - .env

  # Redis para Celery (caché y colas)
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379" # Cambiado de 6379 a 6380 para evitar conflicto
    volumes:
      - redis_data:/data

  # Worker de Celery (para tareas asíncronas)
  celery_worker:
    build: .
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0 # Interno en Docker, no el puerto externo
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A app.core.celery worker --loglevel=info

volumes:
  db_data:
  redis_data:
